"""initial schema

Revision ID: 11a6f542a31b
Revises: 
Create Date: 2026-05-29 16:35:52.599676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11a6f542a31b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger_time', sa.String(length=5), nullable=False),
    sa.Column('interval_hours', sa.Integer(), nullable=False),
    sa.Column('new_sub_strategy', sa.String(length=16), nullable=False),
    sa.Column('new_sub_n', sa.Integer(), nullable=False),
    sa.Column('last_auto_run_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('section', sa.String(length=255), nullable=False),
    sa.Column('list_selectors_json', sa.Text(), nullable=False),
    sa.Column('detail_selectors_json', sa.Text(), nullable=True),
    sa.Column('auto_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('section', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('list_selectors_json', sa.Text(), nullable=True),
    sa.Column('detail_selectors_json', sa.Text(), nullable=True),
    sa.Column('subscription_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index('uq_chat_sessions_sub_confirmed', ['subscription_id'], unique=True, sqlite_where=sa.text("status='confirmed' AND subscription_id IS NOT NULL"))

    op.create_table('fetch_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('enqueued_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('items_added', sa.Integer(), nullable=True),
    sa.Column('items_fetched', sa.Integer(), nullable=True),
    sa.Column('pages_fetched', sa.Integer(), nullable=True),
    sa.Column('stop_reason', sa.String(length=32), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fetch_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fetch_tasks_enqueued_at'), ['enqueued_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fetch_tasks_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('news_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('pub_date', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'url', name='uq_news_sub_url')
    )
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_items_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('news_items_preview',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('pub_date', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'url', name='uq_news_preview_sub_url')
    )
    with op.batch_alter_table('news_items_preview', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_items_preview_subscription_id'), ['subscription_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news_items_preview', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_items_preview_subscription_id'))

    op.drop_table('news_items_preview')
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_items_subscription_id'))

    op.drop_table('news_items')
    with op.batch_alter_table('fetch_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fetch_tasks_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_fetch_tasks_enqueued_at'))

    op.drop_table('fetch_tasks')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index('uq_chat_sessions_sub_confirmed', sqlite_where=sa.text("status='confirmed' AND subscription_id IS NOT NULL"))

    op.drop_table('chat_sessions')
    op.drop_table('subscriptions')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
